### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [kjw16911/CPP202309#4]
### 없는 파일
- challenge/week2/candy.cpp
- challenge/week2/temperature.cpp 
- challenge/week2/temperature2.cpp
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week5/randomMax
    - Error: redefinition of 'value' [line 39]
        - 범위기반 for문에서 이미 value라는 변수를 선언했기 때문에, 그 아래에 int value로 다시 선언하는 것은 잘못된 것입니다. 해당 라인에 value를 선언한 코드를 제거해주세요.
- ERROR in practice/week3/maxvalue
    - Error: expected '>' [line 1]
    - Error: use of undeclared identifier 'cout' [line 8]
    - Error: use of undeclared identifier 'cin' [line 9]
    - Error: use of undeclared identifier 'cout' [line 18]
    - Error: use of undeclared identifier 'endl' [line 18]
        - iostream 헤더파일을 추가하는 코드에 > 가 누락되어, 아래에 cout이나 cin 함수들을 불러오지 못하고 있습니다. 첫번째 라인에 > 를 추가해주세요.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in practice/week3/maxvalue
    - Warning: using directive refers to implicitly-defined namespace 'std' [line 2]
        - iostream 뒤에 > 가 없어, name space를 제대로 사용하지 못하고있습니다. 오타를 수정해주세요. 
- WARNING in project/week8/mud_game
    - Warning: expression result unused [line 214]
       - 해당 라인에 false만 존재합니다. false를 어떻게 사용할지에 대한 코드를 작성해주세요.

**Comment by kjw16911** [comment]
확인하도록 하겠습니다. #4
